logs:
    dir_logs: output/
    model_name: msdn
data:
    dataset: nia
    opts: options/data.yaml
    dataset_option: small # (small | normal | fat)
    batch_size: 1
    use_region: False
model:
    arch: FN_v4
    rpn_opts: options/RPN/rpn.yaml
    # feature vector size
    dim_hr: 512
    dim_ho: 512
    dim_hp: 512
    use_shortcut: True
    pool_size: 7
    op: Sum
    # for both kernel-based attention and Mutan
    dim_mm: 256
    activation: relu
    # Iters for message passing, 0 means disable that
    MPS_iter: 1
    # settings for attention gate
    use_bias: True
    dropout: 0.
    # Settings for inference part
    fusion: PI_v5 # PI is short for [Predicate Inference]
    bottleneck: True
    # loss_weight
    cls_obj: 1.
    cls_pred: 2.
    reg_obj: 0.5

optim:
    lr: 0.01
    lr_decay: 0.1
    lr_decay_epoch: 2
    epochs: 30
    optimizer: 0 # [0: SGD | 1: Adam | 2: Adagrad]
    nesterov: True
    weight_decay: 0.00001
    momentum: 0.9
    clip_gradient: True

